#Seed the Deck

state_capitol_deck = Deck.create(category: 'State Capitols')

state_capitol_deck.cards << Card.create(question: "Alabama", answer: "Montgomery")
state_capitol_deck.cards << Card.create(question: "Alaska", answer: "Juneau")
state_capitol_deck.cards << Card.create(question: "Arizona", answer: "Phoenix")
state_capitol_deck.cards << Card.create(question: "Arkansas", answer: "Little Rock")
state_capitol_deck.cards << Card.create(question: "California", answer: "Sacramento")
state_capitol_deck.cards << Card.create(question: "Colorado", answer: "Denver")
state_capitol_deck.cards << Card.create(question: "Connecticut", answer: "Hartford")
state_capitol_deck.cards << Card.create(question: "Delaware", answer: "Dover")
state_capitol_deck.cards << Card.create(question: "Florida", answer: "Tallahassee")
state_capitol_deck.cards << Card.create(question: "Georgia", answer: "Atlanta")
state_capitol_deck.cards << Card.create(question: "Hawaii", answer: "Honolulu")
state_capitol_deck.cards << Card.create(question: "Idaho", answer: "Boise")
state_capitol_deck.cards << Card.create(question: "Illinois", answer: "Springfield")
state_capitol_deck.cards << Card.create(question: "Indiana", answer: "Indianapolis")
state_capitol_deck.cards << Card.create(question: "Iowa", answer: "Des Moines")
state_capitol_deck.cards << Card.create(question: "Kansas", answer: "Topeka")
state_capitol_deck.cards << Card.create(question: "Kentucky", answer: "Frankfort")
state_capitol_deck.cards << Card.create(question: "Louisiana", answer: "Baton Rouge") 
state_capitol_deck.cards << Card.create(question: "Maine", answer: "Augusta")
state_capitol_deck.cards << Card.create(question: "Maryland", answer: "Annapolis")
state_capitol_deck.cards << Card.create(question: "Massachusetts", answer: "Boston")
state_capitol_deck.cards << Card.create(question: "Michigan", answer: "Lansing")
state_capitol_deck.cards << Card.create(question: "Minnesota", answer: "Saint Paul") 
state_capitol_deck.cards << Card.create(question: "Mississippi", answer: "Jackson")
state_capitol_deck.cards << Card.create(question: "Missouri", answer: "Jefferson City") 
state_capitol_deck.cards << Card.create(question: "Montana", answer: "Helena")
state_capitol_deck.cards << Card.create(question: "Nebraska", answer: "Lincoln")
state_capitol_deck.cards << Card.create(question: "Nevada", answer: "Carson City") 
state_capitol_deck.cards << Card.create(question: "New Hampshire", answer: "Concord") 
state_capitol_deck.cards << Card.create(question: "New Jersey", answer: "Trenton")
state_capitol_deck.cards << Card.create(question: "New Mexico", answer: "Santa Fe")
state_capitol_deck.cards << Card.create(question: "New York", answer: "Albany")
state_capitol_deck.cards << Card.create(question: "North Carolina", answer: "Raleigh")
state_capitol_deck.cards << Card.create(question: "North Dakota", answer: "Bismarck")
state_capitol_deck.cards << Card.create(question: "Ohio", answer: "Columbus")
state_capitol_deck.cards << Card.create(question: "Oklahoma", answer: "Oklahoma City") 
state_capitol_deck.cards << Card.create(question: "Oregon", answer: "Salem")
state_capitol_deck.cards << Card.create(question: "Pennsylvania", answer: "Harrisburg")
state_capitol_deck.cards << Card.create(question: "Rhode Island", answer: "Providence")  
state_capitol_deck.cards << Card.create(question: "South Carolina", answer: "Columbia")
state_capitol_deck.cards << Card.create(question: "South Dakota", answer: "Pierre")  
state_capitol_deck.cards << Card.create(question: "Tennessee", answer: "Nashville")
state_capitol_deck.cards << Card.create(question: "Texas", answer: "Austin")
state_capitol_deck.cards << Card.create(question: "Utah", answer: "Salt Lake City") 
state_capitol_deck.cards << Card.create(question: "Vermont", answer: "Montpelier")
state_capitol_deck.cards << Card.create(question: "Virginia", answer: "Richmond")
state_capitol_deck.cards << Card.create(question: "Washington", answer: "Olympia")
state_capitol_deck.cards << Card.create(question: "West Virginia", answer: "Charleston") 
state_capitol_deck.cards << Card.create(question: "Wisconsin", answer: "Madison")
state_capitol_deck.cards << Card.create(question: "Wyoming", answer: "Cheyenne")

#Seed Users

User.create(name: "Luis Perez", password: "pass", email: "lperez@email.com")
User.create(name: "Harry Boileau", password: "pass", email:"hboleau@email.com")

#Seed Rounds

round1 = Round.create(correct_guess_count: 8, user_id: 1, deck_id: 1)

round1.guesses << Guess.create(answer_input: "Montgomery", correctness: true, card_id: 1)
round1.guesses << Guess.create(answer_input: "Juneau", correctness: true, card_id: 2)
round1.guesses << Guess.create(answer_input: "Phoenix", correctness: true, card_id: 3)
round1.guesses << Guess.create(answer_input: "Little Rock", correctness: true, card_id: 4)
round1.guesses << Guess.create(answer_input: "Sacramento", correctness: true, card_id: 5)
round1.guesses << Guess.create(answer_input: "Denver", correctness: true, card_id: 6)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: true, card_id: 7)
round1.guesses << Guess.create(answer_input: "Dover", correctness: true, card_id: 8)
round1.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 9)
round1.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 10)
round1.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 11)
round1.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 12)
round1.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 13)
round1.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 14)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 15)
round1.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 16)
round1.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 17)
round1.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 18)
round1.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 19)
round1.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 20)
round1.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 21)
round1.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 22)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 23)
round1.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 24)
round1.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 25)
round1.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 26)
round1.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 27)
round1.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 28)
round1.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 29)
round1.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 30)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 31)
round1.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 32)
round1.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 33)
round1.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 34)
round1.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 35)
round1.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 36)
round1.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 37)
round1.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 38)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 39)
round1.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 40)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 41)
round1.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 42)
round1.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 43)
round1.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 44)
round1.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 45)
round1.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 46)
round1.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 47)
round1.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 48)
round1.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 49)
round1.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 50)


round2 = Round.create(correct_guess_count: 10, user_id: 2, deck_id: 1)

round2.guesses << Guess.create(answer_input: "Montgomery", correctness: true, card_id: 1)
round2.guesses << Guess.create(answer_input: "Juneau", correctness: true, card_id: 2)
round2.guesses << Guess.create(answer_input: "Phoenix", correctness: true, card_id: 3)
round2.guesses << Guess.create(answer_input: "Little Rock", correctness: true, card_id: 4)
round2.guesses << Guess.create(answer_input: "Sacramento", correctness: true, card_id: 5)
round2.guesses << Guess.create(answer_input: "Denver", correctness: true, card_id: 6)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: true, card_id: 7)
round2.guesses << Guess.create(answer_input: "Dover", correctness: true, card_id: 8)
round2.guesses << Guess.create(answer_input: "Atlanta", correctness: true, card_id: 9)
round2.guesses << Guess.create(answer_input: "Tallahassee", correctness: true, card_id: 10)
round2.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 11)
round2.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 12)
round2.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 13)
round2.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 14)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 15)
round2.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 16)
round2.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 17)
round2.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 18)
round2.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 19)
round2.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 20)
round2.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 21)
round2.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 22)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 23)
round2.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 24)
round2.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 25)
round2.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 26)
round2.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 27)
round2.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 28)
round2.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 29)
round2.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 30)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 31)
round2.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 32)
round2.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 33)
round2.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 34)
round2.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 35)
round2.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 36)
round2.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 37)
round2.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 38)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 39)
round2.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 40)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 41)
round2.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 42)
round2.guesses << Guess.create(answer_input: "Montgomery", correctness: false, card_id: 43)
round2.guesses << Guess.create(answer_input: "Juneau", correctness: false, card_id: 44)
round2.guesses << Guess.create(answer_input: "Phoenix", correctness: false, card_id: 45)
round2.guesses << Guess.create(answer_input: "Little Rock", correctness: false, card_id: 46)
round2.guesses << Guess.create(answer_input: "Sacramento", correctness: false, card_id: 47)
round2.guesses << Guess.create(answer_input: "Denver", correctness: false, card_id: 48)
round2.guesses << Guess.create(answer_input: "Hartford", correctness: false, card_id: 49)
round2.guesses << Guess.create(answer_input: "Dover", correctness: false, card_id: 50)








